# Generated by Django 4.2.5 on 2023-09-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdPhotos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=200)),
                ('ad_type', models.CharField(max_length=100)),
                ('ad_name', models.CharField(max_length=100)),
                ('ad_image1', models.ImageField(blank=True, null=True, upload_to='ad_images')),
                ('ad_image2', models.ImageField(blank=True, null=True, upload_to='ad_images')),
                ('ad_image3', models.ImageField(blank=True, null=True, upload_to='ad_images')),
                ('ad_image4', models.ImageField(blank=True, null=True, upload_to='ad_images')),
                ('ad_price', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarouselSlider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='home_sliders')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='home_sliders')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='home_sliders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_name', models.CharField(max_length=200)),
                ('post_image', models.ImageField(upload_to='job_posts')),
                ('whatsapp_phone', models.IntegerField(blank=True, null=True)),
                ('mobile_phone', models.IntegerField()),
                ('website', models.URLField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('post_description', models.TextField()),
                ('approved', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
