# Generated by Django 4.2.5 on 2023-10-10 08:58

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobpost_is_active_jobpost_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideshJobPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_category', models.CharField(blank=True, choices=[('CLIENT INTERVIEW', 'Client Interview'), ('CV SELECTION', 'CV Selection'), ('TELEPHONIC INTERVIEW', 'Telephonic Interview'), ('LICENSE HOLDER', 'License Holder')], max_length=100, null=True)),
                ('post_name', models.CharField(max_length=200)),
                ('post_image', models.ImageField(upload_to='job_posts', validators=[job.models.validate_image_size])),
                ('whatsapp_phone', models.IntegerField(blank=True, null=True)),
                ('mobile_phone', models.IntegerField()),
                ('website', models.URLField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('post_description', models.TextField()),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
