# Generated by Django 4.2.5 on 2023-09-24 18:45

from django.db import migrations, models
import django.db.models.deletion
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_jobpost_approved_alter_jobpost_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('job_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_category_name', models.CharField(max_length=100)),
                ('job_category_description', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='post_image',
            field=models.ImageField(upload_to='job_posts', validators=[job.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='job.jobcategory'),
        ),
    ]
