# Generated by Django 4.2.5 on 2023-10-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_videshjobpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videshjobpost',
            name='job_category',
            field=models.CharField(blank=True, choices=[('CI', 'Client Interview'), ('CS', 'CV Selection'), ('TI', 'Telephonic Interview'), ('LH', 'License Holder')], max_length=100, null=True),
        ),
    ]
